name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Bun
        uses: oven-sh/setup-bun@v2

      - name: Instalar dependências
        run: bun install

      - name: Verificar tipos (TypeScript)
        run: bun run typecheck
